language: node_js
node_js:
  - "4.3.2" # AWS Lambda
  - "4"
  - "5"
  - "6"
  - "6.10.3" # AWS Lambda
  - "7"
  - "node"
  - "iojs"

matrix:
  allow_failures:
    node_js:
      - "iojs"
      - "4.3.2"
      - "4"
