language: node_js
node_js:
  - "4.3.2"
  - "4.7.2"
  - "4.7.3"
  - "5.11.0"
  - "5.11.1"
  - "5.12.0"
  - "6.9.1"
  - "6.9.2"
  - "6.9.3"
  - "6.9.4"
  - "6.9.5"
  - "7.3.0"
  - "7.4.0"
  - "7.5.0"

matrix:
  allow_failures:
    node_js:
      - "4.3.2"
      - "4.7.2"
      - "4.7.3"
      - "5.11.0"
      - "5.11.1"
      - "5.12.0"
